[package]
name = "gigabit_latency"
version = "0.1.0"
authors = ["M. Shaaban <m.shaaban@mail.utoronto.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
